// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class MontysGPlayData
{
        public const string leaderboard_lifetime_scrap_award = "CgkIk6bps_wcEAIQBQ"; // <GPGSID>
        public const string achievement_remember_your_vehicles_height = "CgkIk6bps_wcEAIQCg"; // <GPGSID>
        public const string achievement_piston_pusher = "CgkIk6bps_wcEAIQAQ"; // <GPGSID>
        public const string achievement_angry_driver = "CgkIk6bps_wcEAIQAw"; // <GPGSID>
        public const string achievement_tram_catcher = "CgkIk6bps_wcEAIQAA"; // <GPGSID>
        public const string achievement_stunt_driver = "CgkIk6bps_wcEAIQAg"; // <GPGSID>
        public const string leaderboard_piston_pusher = "CgkIk6bps_wcEAIQCA"; // <GPGSID>
        public const string achievement_physics = "CgkIk6bps_wcEAIQBA"; // <GPGSID>

}

